### ISSUE TITLE
Examples does not work with webpack

### ISSUE THREAD

**Issue by BenukEl** [walkermatt/ol-layerswitcher-examples#1]
In try to run de webpack exemple and it does not work for me. 
It seem that ol3-layerswitcher is not download in node_modules directory.

**Comment by BenukEl** [comment]
I made two things. Now it works.
First I delete #ol at the end of the dependency link in package.json
Then I change import link for layerswitcher in main.js with ol3-layerswitcher/src/ol3-layerswitcher

**Comment by walkermatt** [comment]
@BenukEl thanks for spotting this. I'd updated the package name in the ol branch of the layerswitcher but forgotten to update the examples.
